### ISSUE TITLE
Instruct doesn't work 

### ISSUE THREAD

**Issue by ostix360** [Josh-XT/AGiXT#886]
### Description

During instruct a provider I got an error:
...
...
File "/mnt/g/AGiXT/agixt/Memories.py", line 171, in get_nearest_matches_async
    embedding_array = embedding_array.reshape(embedding_array.shape[0], -1)
ValueError: cannot reshape array of size 0 into shape (0,newaxis)

After a few print I conclude that the query_results just above seem to be empty and the last log is  CONTEXT RESULTS: 5.
the printed query_results : {'ids': [[]], 'embeddings': [[]], 'documents': [[]], 'metadatas': [[]], 'distances': None}
This is the best I can do atm

### Steps to Reproduce the Bug

1. Go to interact
2. select instruct 
3. select a provider
4. and Instruct something

### Expected Behavior

Run the instruction

### Operating System

- [X] Linux
- [ ] Microsoft Windows
- [ ] Apple MacOS
- [ ] Android
- [ ] iOS
- [ ] Other

### Python Version

- [ ] Python <= 3.9
- [x] Python 3.10
- [ ] Python 3.11

### Environment Type - Connection

- [X] Local - You run AGiXT in your home network
- [ ] Remote - You access AGiXT through the internet

### Runtime environment

- [ ] Using docker compose
- [X] Using local
- [ ] Custom setup (please describe above!)

### Acknowledgements

- [X] I have searched the existing issues to make sure this bug has not been reported yet.
- [X] I am using the latest version of AGiXT.
- [X] I have provided enough information for the maintainers to reproduce and diagnose the issue.

**Comment by Josh-XT** [comment]
Can you give it another try? I was in the middle of a lot of issues with a chroma update at the time you were having this issue, those issues have been resolved now.

**Comment by ostix360** [comment]
No the problem is still here.
I print the embedding variable and this variable contain a huge list of number and after the query_results is still empty.

**Comment by Josh-XT** [comment]
Found the issue, I think.  Streamlit wasn't sending the user_input on the Instruct mode.  It should be good now.

**Comment by ostix360** [comment]
It's good 
well done!
